Repository meshery-extensions/helm-kanvas-snapshot, pull requests merged in 2025-01, with the labels that each got.

#83 [chore] Update README.md
  README.md
Labels: area/docs

#89 [bug] Update .goreleaser.yml
  .github/.goreleaser.yml
Labels: area/ci, kind/bug

#90 Remove debug statements
  cmd/kanvas-snapshot/cmd.go
Labels: kind/chore
