Repository meshery-extensions/helm-kanvas-snapshot, pull requests merged in 2025-04, with the labels that each got.

#101 Send kanvas snapshot email
  .github/workflows/kanvas.yaml
  Makefile
  cmd/kanvas-snapshot/cmd.go
Labels: area/ci, kind/feature

#114 [Security] Define permissions explicitly
  .github/workflows/labeler.yml
Labels: security

#111 update kanvas snapshot version
  .github/workflows/kanvas.yaml
Labels: area/ci, kind/chore

#115 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: area/ci

#118 [CI] Add E2E Test
  .github/workflows/e2e-test.yaml
  Makefile
  cmd/kanvas-snapshot/cmd.go
  plugin.yaml
  scripts/e2e.sh
  scripts/install-binary.sh
  scripts/utils.sh
Labels: area/ci, area/tests

#120 [CI] Update e2e-test.yaml
  .github/workflows/e2e-test.yaml
Labels: area/ci

#121 [chore] Update meshery to meshery-extensions
  .github/security-insights.yml
  .github/workflows/build-and-release-snapshot-plugin.yml
  .github/workflows/error-codes-updater.yaml
  .github/workflows/first-time-contributor.yml
  .github/workflows/go-testing-ci.yml
  .github/workflows/golangci-lint.yml
  Makefile
  README.md
  cmd/kanvas-snapshot/cmd.go
  go.mod
  main.go
  plugin.yaml
  scripts/utils.sh
Labels: area/ci, kind/chore

#122 [chore] Fix Lint
  .github/.goreleaser.yml
  cmd/kanvas-snapshot/cmd.go
  go.mod
Labels: area/ci, kind/chore
