Repository meshery-extensions/helm-kanvas-snapshot, pull requests merged in 2025-02, with the labels that each got.

#95 Update Kanvas Snapshot version
  .github/workflows/kanvas.yaml
Labels: area/ci, kind/chore

#96 [chore] Fix Failing Release
  .github/workflows/build-and-release-snapshot-plugin.yml
  .github/workflows/error-codes-updater.yaml
  .github/workflows/go-testing-ci.yml
  .github/workflows/golangci-lint.yml
  cmd/kanvas-snapshot/cmd.go
  go.mod
Labels: area/ci

#97 [chore] Fix upload endpoint
  cmd/kanvas-snapshot/cmd.go
Labels: kind/chore

#100 Update artifact repository ID to the correct Helm Kanvas Snapshot repo ID
  artifacthub-repo.yml
Labels: area/ci, kind/chore
